### PR TITLE
Adding the blanks to the mapper

### PR DESCRIPTION
**Pull request by josenavas**
During the tests with the wet lab we noticed that the blanks where not showing on the dropdown list.

Adding them here.

### CODE REVIEW

**Comment by wasade** [comment]
The test failures appear to be relevant

**Comment by wasade** [comment]
Failures look real

**Comment by tanaes** [comment]
I think this test is failing due to a change in the DB in https://github.com/biocore/american-gut-web/pull/667/files#diff-4a23f2583bf5ae8800eae5c5c77272afL23075 and should pass when merged with the updated test code for `test_normalize_shotgun_plate`.

**Comment by josenavas** [comment]
💥 Can somebody merge?

**Pull request merged**
