### PR TITLE
Let's try this. py2 utf-8 handling is so broken.

### PR DESCRIPTION
**Pull request by wasade**
@EmbrietteH @sjanssen2 @josenavas this I think solves the utf-8 issue from this morning.

### CODE REVIEW

**Comment by sjanssen2** [comment]
looks good to me. Am I right that we now have utf-8 'state's? What about the other fields, like 'name', 'address', 'city', ... ?

**Comment by wasade** [comment]
We do. I modified so geocode information is always decoded. Participant names should already be. What we really need to do is get away from py2 as its handling of ascii and utf-8 is horrible.

**Comment by EmbrietteH** [comment]
Thanks both of you! Good to merge?

**Comment by sjanssen2** [comment]
:+1: good to merge.

**Pull request merged**
