### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by sjanssen2**

### CODE REVIEW

**Comment by sjanssen2** [comment]
@wasade @josenavas I don't understand how the coverage is computed. How can the file knimin/lib/string_converter.py have a coverage of 38.89% after I commented all tests out in the according knimin/lib/tests/test_string_converter.py ?

**Comment by sjanssen2** [comment]
I also don't understand why coverage is not 100%, because it looks to me that all functions are triggered more than once.

**Comment by wasade** [comment]
Indirect execution, eg https://github.com/biocore/labadmin/blob/master/knimin/lib/data_access.py#L1048

**Comment by sjanssen2** [comment]
Oh I see. I commented out all those lines, because I don't understand why the coverage is not 100% for this module. Might it be the case, that the according unit tests in knimin/lib/tests/test_string_converter.py are never executed? If so, is that a bug in some config file?

**Comment by wasade** [comment]
not sure of a config file which would effect this, only one i can think that might is [here](https://github.com/biocore/labadmin/blob/master/.coveragerc). how does coverage look when you run locally? if you run the tests directly, do they actually run?

**Comment by sjanssen2** [comment]
I found the problem, the executable bit for this test file was set, thus nose did not want to run these tests :-)

**Comment by wasade** [comment]
i love and hate nose...

**Comment by wasade** [comment]
good find btw :)

**Pull request closed without merging**
