### PR TITLE
Add subprojects listing to AG scanned barcodes

### PR DESCRIPTION
**Pull request by squirrelo**
Makes subprojects prominent on the barcode scan page.

### CODE REVIEW

**Comment by squirrelo** [comment]
Ping @mortonjt @EmbrietteH

**Comment by squirrelo** [comment]
Ping @mortonjt @EmbrietteH

**Comment by squirrelo** [comment]
Ping @mortonjt @EmbrietteH

**Comment by EmbrietteH** [comment]
@mortonjt please review.

**Comment by josenavas** [comment]
👍  but I would recommend another developer to take a look

**Comment by wasade** [comment]
:+1:

@squirrelo to verify, has the wet lab team taken a look?

**Comment by squirrelo** [comment]
Yup, good with it.

**Pull request merged**
