### PR TITLE
In mem zip

### PR DESCRIPTION
**Pull request by mortonjt**

### CODE REVIEW

**Comment by mortonjt** [comment]
The test that failed is in `test_geocode_nonmock `, which is not addressed in the PR.  

This should be good for review

**Comment by wasade** [comment]
failure on gilman dr zip code?

**Comment by mortonjt** [comment]
the zip code.  Must be based on old code.  I'll try to resubmit this PR after tomorrow.

**Comment by josenavas** [comment]
@mortonjt can you pull from upstream/master to make sure that you've the latest code? I think I fixed that issue few weeks ago.

**Comment by mortonjt** [comment]
I'm going to close and push out a new issue

**Pull request closed without merging**
