### PR TITLE
WIP Plate mapper OOP and QUnit system set up and question

### PR DESCRIPTION
**Pull request by qiyunzhu**
Hello all, I set up a functional JavaScript unit test system. It includes an **index.html** to fire all tests, a **test_xxx.js** for each **xxx.js**. Thanks to @ElDeveloper 's kind instruction. The system was largely mimicing that of Emperor. I used the lastest QUnit 2.x, which has somehow different [grammer](https://qunitjs.com/upgrade-guide-2.x/) comparing to Emperor's QUnit 1.x, though.

Meanwhile I started to object-oriented JavaScript. I created a very small test page **pm_plate_map.html**, a single object "**plateMap**", and a single function "**printID**", which retrieves a plate's name by its ID via Ajax and prints on to the page. I was glad to see it worked.

However, I struggled with the unit test on it. Because Ajax calls are asynchronous, QUnit did the test before it actually finished. I already did research but couldn't get a working solution. Please see **test_pm_plate_map.js** for details.

I would appreciate if anyone can inspire me on this!

(Note: this PR is dependent on PR [#153](https://github.com/biocore/labadmin/pull/153). If anyone can merge that, there will be lot less changes in the current one.)

### CODE REVIEW

**Comment by ElDeveloper** [comment]
@qiyunzhu can you solve the conflicts in this branch? (I think it should suffice to pull from the `plate-mapper-kiwi` branch and pushing back up to the `plate-mapper-oop` branch).

**Comment by qiyunzhu** [comment]
@ElDeveloper Conflicts solved. I am still struggling with ajax...

**Comment by ElDeveloper** [comment]
Thanks @qiyunzhu, for some reason the commits from previous PRs are still showing up in this PR. Do you have any idea of what that may be happening?

**Comment by qiyunzhu** [comment]
@EIDeveloper eh I honestly have no idea. I did pull from upstream with the last PR merged, then push to a new branch in my repo, then pull request.

**Comment by josenavas** [comment]
@qiyunzhu did you pull from upstream/plate-mapper-kiwi or from master? i.e. you should run `git pull upstream plate-mapper-kiwi` and then `git push origin plate-mapper-oop`

**Comment by qiyunzhu** [comment]
@josenavas I think I did -kiwi. But maybe let me do it again to clear the confusion.

**Comment by ElDeveloper** [comment]
@qiyunzhu, I still see those additional commits.

**Comment by wasade** [comment]
Superseded by labman

**Pull request closed without merging**
