### PR TITLE
added license file and qunit test files

### PR DESCRIPTION
**Pull request by qiyunzhu**
We are adding QUnit to the repo, and we are setting up Travis to execute a mock-up test. We also added a license file (includes licenses for chosen, jquery and qunit).

### CODE REVIEW

**Comment by qiyunzhu** [comment]
I paired programmed this with @ElDeveloper, can someone else review this please?

**Comment by antgonza** [comment]
Tests are failing, is that expected?

**Comment by qiyunzhu** [comment]
@antgonza Python tests are supposed to fail (because I added a patch to american-gut-web, but didn't update labadmin), but we expect JavaScript tests to pass (which seems to be the case now).

**Comment by antgonza** [comment]
K, thanks.

**Comment by ElDeveloper** [comment]
Thanks!

**Comment by qiyunzhu** [comment]
Thank you!

**Pull request merged**
