### PR TITLE
Give benefit of the doubt if missing info

### PR DESCRIPTION
**Pull request by squirrelo**
This modifies the logic for correct age to not assume undefined age or weight means we can't correct the age.

### CODE REVIEW

**Comment by wasade** [comment]
what motivated this?

**Comment by squirrelo** [comment]
Talk with @JWDebelius to get it in line with original notebook.

**Comment by EmbrietteH** [comment]
@JWDebelius please check and verify this is in line with what you need.

**Comment by jwdebelius** [comment]
Let's hold off until the next meeting, as we sort out how we're going to define subsets. I think the age_corrected probably also falls into a subset, and may be better defined there...

**Comment by squirrelo** [comment]
Closed in favor of moving this out to a notebook.

**Pull request closed without merging**
