### PR TITLE
only decode str or unicode

### PR DESCRIPTION
**Pull request by wasade**

### CODE REVIEW

**Comment by josenavas** [comment]
👍

**Comment by mortonjt** [comment]
👍 once the tests pass

**Comment by josenavas** [comment]
@wasade can you check the tests?

**Comment by wasade** [comment]
@sjanssen2, can you look at the [failure](https://travis-ci.org/biocore/labadmin/builds/170221322#L349), any idea?

**Comment by wasade** [comment]
Lets see if that does it...

**Comment by sjanssen2** [comment]
I fixed the failing test: https://github.com/biocore/labadmin/pull/157

**Pull request merged**
