### PR TITLE
TST: Add tests for squash barcodes

### PR DESCRIPTION
**Pull request by ElDeveloper**
These tests are minimal, and I think it's as far as we can go, but I'm open to other suggestions.

### CODE REVIEW

**Comment by josenavas** [comment]
👍

**Comment by mortonjt** [comment]
Looks like there is 1 failing test and some flake8 errors

**Comment by ElDeveloper** [comment]
Thanks for the reviews, just fixed the flake8 errors.

**Comment by mortonjt** [comment]
👍

**Pull request merged**
