### PR TITLE
Fix list issue with project summary page

### PR DESCRIPTION
**Pull request by squirrelo**
Need to pas a list of projects, not just a project. This fixes that call.

### CODE REVIEW

**Comment by EmbrietteH** [comment]
Ping @mortonjt

**Comment by squirrelo** [comment]
Ping @mortonjt again

**Comment by squirrelo** [comment]
Ping @mortonjt again

**Comment by squirrelo** [comment]
Ping @EmbrietteH @mortonjt @wasade

**Comment by josenavas** [comment]
👍  I'm assuming that a small test can't be added to check that this doesn't happen again?

**Pull request merged**
